safe:        false
auto:        true
server:      false
server_port: 4000
baseurl:    /jekyll_demo
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
permalink:   date
